theme: jekyll-theme-hacker
lang: cs_CZ
title: mmares.cz - Osobní weblog
description: IT & general stuff
url: https://mmares.cz
author: Miroslav Mareš
email: mmares.trinity@gmail.com
timezone: Europe/Prague
github:
  user_url: https://github.com/TrinityCoder
gitlab:
  user_url: https://gitlab.com/mmares.trinity
header_pages:
  - o-mne.md
google_analytics: UA-119604643-2
markdown: kramdown
plugins:
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      author: "Miroslav Mareš"
      comments: true
      use_math: false
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      ld_json_type: BlogPosting
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      ld_json_type: WebPage
  - scope:
      path: "assets/no-robots/no-sitemap"
    values:
      sitemap: false
