theme: jekyll-theme-hacker
lang: cs
title: mmares.cz - Osobní IT blog
description: O Linuxu, C++, programování...
author: Miroslav Mareš
email: mmares.trinity@gmail.com
gitlab:
  repository_url: https://gitlab.com/mmares.trinity
header_pages:
  - o-mne.md
