theme: jekyll-theme-hacker
lang: cs
title: mmares.cz - Osobní weblog
description: IT & general stuff
author: Miroslav Mareš
email: mmares.trinity@gmail.com
timezone: Europe/Prague
github:
  user_url: https://github.com/TrinityCoder
gitlab:
  user_url: https://gitlab.com/mmares.trinity
header_pages:
  - o-mne.md
google_analytics: UA-119604643-2
markdown: kramdown
